#ifndef BINDINGS_H
#define BINDINGS_H

#include "MachDeps.h"

#define SUPPORTS_MULTI_GEOM_FIELDS ((GDAL_VERSION_MAJOR >= 1) && (GDAL_VERSION_MINOR >= 11))

#define SUPPORTS_64_BIT_INT_FIELDS (GDAL_VERSION_MAJOR >=2)
#define SUPPORTS_NULLABLE_FIELD_DEFS (GDAL_VERSION_MAJOR >=2)

#define SUPPORTS_WORD_FIELDS ((WORD_SIZE_IN_BITS < 64) || SUPPORTS_64_BIT_INT_FIELDS)

#endif
