-- GENERATED by C->Haskell Compiler, version 0.16.4 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "src/OSGeo/OSR/Internal.chs" #-}{-# LANGUAGE ForeignFunctionInterface , BangPatterns  #-}

module OSGeo.OSR.Internal (
    SpatialReference
  , fromWkt
  , fromProj4
  , fromEPSG
  , exportToPrettyWkt
) where

import Control.Applicative ((<$>), (<*>))
import Control.Exception (throw, catchJust, fromException)
import Control.Monad (liftM)

import Foreign.C.String (withCString, CString, peekCString)
import Foreign.C.Types (CDouble(..), CInt(..), CChar(..))
import Foreign.Ptr (Ptr, FunPtr, castPtr, nullPtr, freeHaskellFunPtr)
import Foreign.Storable (Storable(..))
import Foreign.ForeignPtr (ForeignPtr, withForeignPtr, newForeignPtr
                          ,mallocForeignPtrArray)
import Foreign.Marshal.Alloc (alloca)
import Foreign.Marshal.Array (allocaArray)
import Foreign.Marshal.Utils (toBool, fromBool)

import System.IO.Unsafe (unsafePerformIO)

import OSGeo.Util
import OSGeo.OGR 


newtype SpatialReference = SpatialReference (ForeignPtr (SpatialReference))
withSpatialReference (SpatialReference fptr) = withForeignPtr fptr
{-# LINE 33 "src/OSGeo/OSR/Internal.chs" #-}

instance Show SpatialReference where
   show s = exportToPrettyWkt s False

exportToPrettyWkt :: SpatialReference -> Bool -> String
exportToPrettyWkt s simpl = unsafePerformIO $
    alloca $ \ptr -> do
      err <- withSpatialReference s $ \s' ->
               oSRExportToPrettyWkt s' ptr (fromBool simpl)
      case toEnumC err of
         None -> do str <- peek ptr
                    wkt <- peekCString str
                    vSIFree (castPtr str)
                    return wkt
         err' -> return "<error converting to pretty WKT"

   

foreign import ccall unsafe "ogr_srs_api.h OSRNewSpatialReference"
  c_newSpatialRef :: CString -> IO (Ptr SpatialReference)

foreign import ccall "ogr_srs_api.h &OSRDestroySpatialReference"
  c_destroySpatialReference :: FunPtr (Ptr SpatialReference -> IO ())

newSpatialRefHandle :: Ptr SpatialReference
  -> IO SpatialReference
newSpatialRefHandle p
  = if p==nullPtr
       then throw $ OGRException Failure "could not allocate SpatialReference"
       else SpatialReference <$> newForeignPtr c_destroySpatialReference p

emptySpatialRef :: IO SpatialReference
emptySpatialRef = c_newSpatialRef (castPtr nullPtr) >>= newSpatialRefHandle

fromWkt, fromProj4 :: String -> Either Error SpatialReference
fromWkt s
  = unsafePerformIO $ catchJust guardIt createIt (return . Left)
  where
    createIt
      = withCString s $ \s' ->
        c_newSpatialRef s' >>= newSpatialRefHandle >>= return . Right
    guardIt e
      = case fromException e of
          Nothing                   -> Nothing
          Just (OGRException err _) -> Just err

fromProj4 = fromImporter importFromProj4

fromEPSG :: Int -> Either Error SpatialReference
fromEPSG = fromImporter importFromEPSG

fromImporter ::
  (SpatialReference -> a -> IO CInt)
  -> a
  -> Either Error SpatialReference
fromImporter f s = unsafePerformIO $ do
    r <- emptySpatialRef
    err <- liftM toEnumC $ f r s
    case err of
      None -> return $ Right r
      e    -> return $ Left e

importFromProj4 :: SpatialReference -> String -> IO (CInt)
importFromProj4 a1 a2 =
  withSpatialReference a1 $ \a1' -> 
  withCString a2 $ \a2' -> 
  importFromProj4'_ a1' a2' >>= \res ->
  let {res' = id res} in
  return (res')
{-# LINE 97 "src/OSGeo/OSR/Internal.chs" #-}

importFromEPSG :: SpatialReference -> Int -> IO (CInt)
importFromEPSG a1 a2 =
  withSpatialReference a1 $ \a1' -> 
  let {a2' = fromIntegral a2} in 
  importFromEPSG'_ a1' a2' >>= \res ->
  let {res' = id res} in
  return (res')
{-# LINE 100 "src/OSGeo/OSR/Internal.chs" #-}

foreign import ccall unsafe "OSGeo/OSR/Internal.chs.h OSRExportToPrettyWkt"
  oSRExportToPrettyWkt :: ((Ptr (SpatialReference)) -> ((Ptr (Ptr CChar)) -> (CInt -> (IO CInt))))

foreign import ccall unsafe "OSGeo/OSR/Internal.chs.h VSIFree"
  vSIFree :: ((Ptr ()) -> (IO ()))

foreign import ccall unsafe "OSGeo/OSR/Internal.chs.h OSRImportFromProj4"
  importFromProj4'_ :: ((Ptr (SpatialReference)) -> ((Ptr CChar) -> (IO CInt)))

foreign import ccall unsafe "OSGeo/OSR/Internal.chs.h OSRImportFromEPSG"
  importFromEPSG'_ :: ((Ptr (SpatialReference)) -> (CInt -> (IO CInt)))
